plugins {
    id 'java'
    id 'application'
}

group = 'ru.nsu.chebotareva'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

application {
    mainClass = 'ru.nsu.chebotareva.task3.Main'
}

dependencies {
    implementation 'org.postgresql:postgresql:42.7.2'
    implementation 'com.zaxxer:HikariCP:5.1.0'
    implementation 'org.slf4j:slf4j-simple:2.0.12'
}

test {
    useJUnitPlatform()
}
