version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: task3-postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - task3-pgdata:/var/lib/postgresql/data

volumes:
  task3-pgdata:
